### PR TITLE
Initial support for Fpc/LCL/Lazarus

### PR DESCRIPTION
**Pull request by DomenicoMammola**
These changes allow to compile the component with the last version of Lazarus/fpc.
The component in Lazarus is quite fully functional (on Windows) even if there are some issues (trasparent background does not work correctly) and it is not still full tested.

### CODE REVIEW

**Comment by norgepaul** [comment]
Hi,

This is great. However, I think I would like to keep the main repo Delphi only. How about making a fork for the Fpc version?

/Paul

**Comment by DomenicoMammola** [comment]
Hi Paul, 
ok, it's fine for me to keep them separated, as you prefer.
I will merge the port-to-lazarus branch to master on my repo and update the readme file.
I am wondering if you could add a small note somewhere in the documentation of your component to indicate the existance of the porting attemp. Just to route fpc developers to the LCL repo.
TIA, 
Domenico

PS
I will also close the pull request.

**Comment by landrix** [comment]
Can you give the URL to your port for the documentation?

**Comment by DomenicoMammola** [comment]
https://github.com/DomenicoMammola/TChromeTabs

**Pull request closed without merging**
